
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.13.9+e0f243f1e for .NET Framework
      Build started 4/12/2025 11:01:15 AM.
      
      Project "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\CFD\\Inviscid_Euler_Solver\\CMakeFiles\\4.0.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      VcpkgTripletSelection:
        Using triplet "x64-windows" from "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\"
        Using normalized configuration "Release"
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\CL.exe /c /I"C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\include" /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\lib" /LIBPATH:"C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\lib\\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\lib\\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\CFD\\Inviscid_Euler_Solver\\CMakeFiles\\4.0.0\\CompilerIdCXX\\CompilerIdCXX.exe
      AppLocalFromInstalled:
        pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\scripts\\buildsystems\\msbuild\\applocal.ps1" "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\CFD\\Inviscid_Euler_Solver\\CMakeFiles\\4.0.0\\CompilerIdCXX\\CompilerIdCXX.exe" "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\bin" "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.write.1u.tlog" "Debug\\vcpkg.applocal.log"
        'pwsh.exe' is not recognized as an internal or external command,
        operable program or batch file.
        The command "pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\scripts\\buildsystems\\msbuild\\applocal.ps1" "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\CFD\\Inviscid_Euler_Solver\\CMakeFiles\\4.0.0\\CompilerIdCXX\\CompilerIdCXX.exe" "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\bin" "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.write.1u.tlog" "Debug\\vcpkg.applocal.log"" exited with code 9009.
        "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\scripts\\buildsystems\\msbuild\\applocal.ps1" "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\CFD\\Inviscid_Euler_Solver\\CMakeFiles\\4.0.0\\CompilerIdCXX\\CompilerIdCXX.exe" "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\bin" "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.write.1u.tlog" "Debug\\vcpkg.applocal.log"
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.43.34808\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Done Building Project "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\CFD\\Inviscid_Euler_Solver\\CMakeFiles\\4.0.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:05.36
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/jmmcl/OneDrive/Desktop/Project/CFD/Inviscid_Euler_Solver/CMakeFiles/4.0.0/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/jmmcl/OneDrive/Desktop/Project/CFD/Inviscid_Euler_Solver/CMakeFiles/CMakeScratch/TryCompile-49unnm"
      binary: "C:/Users/jmmcl/OneDrive/Desktop/Project/CFD/Inviscid_Euler_Solver/CMakeFiles/CMakeScratch/TryCompile-49unnm"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/jmmcl/OneDrive/Desktop/Project/CFD/Inviscid_Euler_Solver/CMakeFiles/CMakeScratch/TryCompile-49unnm'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_63c12.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.13.9+e0f243f1e for .NET Framework
        Build started 4/12/2025 11:01:21 AM.
        
        Project "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\CFD\\Inviscid_Euler_Solver\\CMakeFiles\\CMakeScratch\\TryCompile-49unnm\\cmTC_63c12.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_63c12.dir\\Debug\\".
          Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
          Creating directory "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\CFD\\Inviscid_Euler_Solver\\CMakeFiles\\CMakeScratch\\TryCompile-49unnm\\Debug\\".
          Creating directory "cmTC_63c12.dir\\Debug\\cmTC_63c12.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_63c12.dir\\Debug\\cmTC_63c12.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
          Touching "cmTC_63c12.dir\\Debug\\cmTC_63c12.tlog\\unsuccessfulbuild".
        VcpkgTripletSelection:
          Using triplet "x64-windows" from "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\"
          Using normalized configuration "Debug"
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\CL.exe /c /I"C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\include" /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_63c12.dir\\Debug\\\\" /Fd"cmTC_63c12.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.43.34808 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /I"C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\include" /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_63c12.dir\\Debug\\\\" /Fd"cmTC_63c12.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\CFD\\Inviscid_Euler_Solver\\CMakeFiles\\CMakeScratch\\TryCompile-49unnm\\Debug\\cmTC_63c12.exe" /INCREMENTAL /ILK:"cmTC_63c12.dir\\Debug\\cmTC_63c12.ilk" /NOLOGO /LIBPATH:"C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\debug\\lib" /LIBPATH:"C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\debug\\lib\\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\debug\\lib\\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/jmmcl/OneDrive/Desktop/Project/CFD/Inviscid_Euler_Solver/CMakeFiles/CMakeScratch/TryCompile-49unnm/Debug/cmTC_63c12.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/jmmcl/OneDrive/Desktop/Project/CFD/Inviscid_Euler_Solver/CMakeFiles/CMakeScratch/TryCompile-49unnm/Debug/cmTC_63c12.lib" /MACHINE:X64  /machine:x64 cmTC_63c12.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_63c12.vcxproj -> C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\CFD\\Inviscid_Euler_Solver\\CMakeFiles\\CMakeScratch\\TryCompile-49unnm\\Debug\\cmTC_63c12.exe
        AppLocalFromInstalled:
          pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\scripts\\buildsystems\\msbuild\\applocal.ps1" "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\CFD\\Inviscid_Euler_Solver\\CMakeFiles\\CMakeScratch\\TryCompile-49unnm\\Debug\\cmTC_63c12.exe" "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\debug\\bin" "cmTC_63c12.dir\\Debug\\cmTC_63c12.tlog\\cmTC_63c12.write.1u.tlog" "cmTC_63c12.dir\\Debug\\vcpkg.applocal.log"
          'pwsh.exe' is not recognized as an internal or external command,
          operable program or batch file.
          The command "pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\scripts\\buildsystems\\msbuild\\applocal.ps1" "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\CFD\\Inviscid_Euler_Solver\\CMakeFiles\\CMakeScratch\\TryCompile-49unnm\\Debug\\cmTC_63c12.exe" "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\debug\\bin" "cmTC_63c12.dir\\Debug\\cmTC_63c12.tlog\\cmTC_63c12.write.1u.tlog" "cmTC_63c12.dir\\Debug\\vcpkg.applocal.log"" exited with code 9009.
          "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\scripts\\buildsystems\\msbuild\\applocal.ps1" "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\CFD\\Inviscid_Euler_Solver\\CMakeFiles\\CMakeScratch\\TryCompile-49unnm\\Debug\\cmTC_63c12.exe" "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\C_Plus_Plus_Libraries\\vcpkg-master\\installed\\x64-windows\\debug\\bin" "cmTC_63c12.dir\\Debug\\cmTC_63c12.tlog\\cmTC_63c12.write.1u.tlog" "cmTC_63c12.dir\\Debug\\vcpkg.applocal.log"
        FinalizeBuildStatus:
          Deleting file "cmTC_63c12.dir\\Debug\\cmTC_63c12.tlog\\unsuccessfulbuild".
          Touching "cmTC_63c12.dir\\Debug\\cmTC_63c12.tlog\\cmTC_63c12.lastbuildstate".
        Done Building Project "C:\\Users\\jmmcl\\OneDrive\\Desktop\\Project\\CFD\\Inviscid_Euler_Solver\\CMakeFiles\\CMakeScratch\\TryCompile-49unnm\\cmTC_63c12.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:03.51
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:227 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.43.34808/bin/HostX64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CMakeDetermineLinkerId.cmake:36 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:264 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Running the CXX compiler's linker: "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.43.34808/bin/HostX64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.43.34808.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
